Controllers/RentController.cs
using Microsoft.AspNet.Identity;
using RVASProject.Data;
using RVASProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace RVASProject.Controllers
{
    public class RentController : Controller
    {
        private readonly RentACarContext _context;

        public RentController()
        {
            _context = new RentACarContext();
        }

        public ActionResult Index(int carId)
        {
            ViewBag.CarId = carId;
            var car = _context.Cars.FirstOrDefault(x=>x.Id == carId);
            var userName = User.Identity.Name;
            var customer = _context.Customers.FirstOrDefault(x => x.FirstName == userName);
            var RentalModel = new Rental { Car = car, Customer = customer };

            return View(RentalModel);

        }
        
        public ActionResult Create(int carId)
        {
            ViewBag.CarId = carId;
            return View("Index");
        }

        
        [HttpPost]
        public ActionResult Create(Rental rental)
        {
            if (ModelState.IsValid)
            {
                var existingCar = _context.Cars.FirstOrDefault(c => c.Id == rental.CarId);
                if (existingCar != null)
                {

                    rental.CarId = existingCar.Id;
                }
                else
                {
                    return View("Error", "Rental");
                    
                }


                var userName = User.Identity.Name;
                var customer = _context.Customers.FirstOrDefault(x => x.FirstName == userName);
                if (customer == null)
                {
                    
                    customer = new Customer { FirstName = userName }; 

                    _context.Customers.Add(customer);
                    _context.SaveChanges(); 
                }

                var id = customer.Id;
                rental.CustomerId = id;
               
                _context.Rentals.Add(rental);
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");

            }
            
            ViewBag.CustomerId = new SelectList(_context.Customers, "CustomerId", "Name", rental.CustomerId);
            return View(rental);
        }
      
        public ActionResult Delete(int? carId, int? customerId)
        {
            var rental = _context.Rentals.FirstOrDefault(x => x.CarId == carId || x.CustomerId == customerId);
            if (rental == null)
            {
                return HttpNotFound();
            }

            return View(rental);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            var rental = _context.Rentals.Find(id);
            if (rental == null)
            {
                return HttpNotFound();
            }

            _context.Rentals.Remove(rental);
            _context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        public ActionResult ShowAll()
        {
            var rentals = _context.Rentals.Include("Car").Include("Customer").ToList();

            return View(rentals); 
        }

    }
}

Views/Rent/Delete.cshtml
@model RVASProject.Models.Rental

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rental</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Car.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnTime)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Rent", new { id = Model.Id}, FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Rent/Index.cshtml
@model RVASProject.Models.Rental

@{
    ViewBag.Title = "Create Rental";
}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

@Scripts.Render("~/bundles/modernizr") 
@Scripts.Render("~/Scripts/jquery.datetimepicker.full.min.js")

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.3.7/jquery.datetimepicker.min.css" />

<style>
    #customersTable {
        border-collapse: collapse;
        width: 100%;
    }

        #customersTable th, #customersTable td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }

        #customersTable th {
            background-color: #f2f2f2;
        }
</style>


<script type="text/javascript">
    $(document).ready(function () {
        $('#datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD HH:mm'
        });
    });
</script>

<h2>Rent Car</h2>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            ID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>
        <dt class="col-sm-2">
            CID
        </dt>
        @*<dd class="col-sm-10">
                @Html.DisplayFor(model => model.Car.Id)
            </dd>*@
        <dt class="col-sm-2">
            Make
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Make)
        </dd>
        <dt class="col-sm-2">
            Model
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Model)
        </dd>
        <dt class="col-sm-2">
            Year
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Car.Year)
        </dd>
    </dl>
</div>

@using (Html.BeginForm("Create", "Rent", FormMethod.Post))
{

    @Html.HiddenFor(model => model.CarId, new { Value = Model.Car.Id })
    @*<div class="form-group">
            @Html.LabelFor(model => model.Customer.Id, "Customer ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Customer.Id, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.RentTime, "RentTime", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.RentTime, "{0:yyyy-MM-dd HH:mm}", new { @class = "form-control datetimepicker" })
            @Html.ValidationMessageFor(model => model.RentTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ReturnTime, "ReturnTime", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ReturnTime, "{0:yyyy-MM-dd HH:mm}", new { @class = "form-control datetimepicker" })
            @Html.ValidationMessageFor(model => model.ReturnTime, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.HiddenFor(model => model.Id)
    </div>

    @*<div class="form-group">
            @Html.HiddenFor(model => model.Car.Id)
        </div>*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Rent" class="btn btn-primary" />
        </div>
    </div>
}

Views/Rent/ShowAll.cshtml
@model IEnumerable<RVASProject.Models.Rental>

@{
    ViewBag.Title = "ShowAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ShowAll</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Car.Make)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RentTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Car.Make)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RentTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id}) |
            @Html.ActionLink("Delete", "Delete", new { carId = item.CarId, customerId = item.CustomerId })
        </td>
    </tr>
}

</table>